sudo: required
services:
        - docker
before_install:
        - docker build -t parthsujalshah/react-test -f ./client/Dockerfile.dev ./client

        scripts:
                - docker run parthsujalshah/react-test npm test -- --coverage

after_success:
        - docker build -t parthsujalshah/multi-client ./client
        - docker build -t parthsujalshah/multi-nginx ./nginx
        - docker build -t parthsujalshah/multi-server ./server
        - docker build -t parthsujalshah/multi-worker ./worker
        # login to docker cli
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        # push to docker hub
        - docker push parthsujalshah/multi-client
        - docker push parthsujalshah/multi-nginx
        - docker push parthsujalshah/multi-server
        - docker push parthsujalshah/multi-worker
